//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetAllocation
    {
        public int Id { get; set; }
        public int AssetId { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<System.DateTime> AtAllocation { get; set; }
        public Nullable<System.DateTime> AtEndAllocation { get; set; }
        public Nullable<System.DateTime> AtScheduledEndAllocation { get; set; }
        public Nullable<System.DateTime> AtCreate { get; set; }
        public Nullable<System.DateTime> AtUpdate { get; set; }
    }
}
