//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceErrorReport
    {
        public int Id { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public Nullable<int> HandlerId { get; set; }
        public Nullable<System.DateTime> AtReport { get; set; }
        public Nullable<System.DateTime> AtReciver { get; set; }
        public Nullable<System.DateTime> AtHandler { get; set; }
        public Nullable<System.DateTime> AtCreate { get; set; }
        public Nullable<System.DateTime> AtUpdate { get; set; }
    }
}
