//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagementAssignment
    {
        public int Id { get; set; }
        public int ManagerId { get; set; }
        public int RoomId { get; set; }
        public Nullable<System.DateTime> AtAssignment { get; set; }
        public Nullable<System.DateTime> AtEndAssignment { get; set; }
        public Nullable<System.DateTime> AtScheduledEndAssignment { get; set; }
        public Nullable<System.DateTime> AtCreate { get; set; }
        public Nullable<System.DateTime> AtUpdate { get; set; }
    }
}
