//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string ReportId { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> NumbersOfNewAsset { get; set; }
        public Nullable<int> NumbersOfLiquidation { get; set; }
        public Nullable<int> NumbersOfStopUsing { get; set; }
        public Nullable<int> NumbersOfAsset { get; set; }
        public Nullable<decimal> TotalNewAsset { get; set; }
        public Nullable<decimal> TotalLiquidation { get; set; }
        public Nullable<decimal> TotalStopUsing { get; set; }
        public Nullable<decimal> TotalRepair { get; set; }
        public Nullable<System.DateTime> AtCreate { get; set; }
        public Nullable<System.DateTime> AtUpdate { get; set; }
    }
}
