//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCategory
    {
        public int Id { get; set; }
        public string ReportId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Numbers { get; set; }
        public Nullable<decimal> TotalIncrease { get; set; }
        public Nullable<int> NumberIncrease { get; set; }
        public Nullable<decimal> TotalDecrease { get; set; }
        public Nullable<int> NumberDecrease { get; set; }
    }
}
